export const BIKE_TYPES = [
  "CITY_BIKE",
  "ROAD_BIKE",
  "MOUNTAIN_BIKE",
  "HYBRID_BIKE",
  "FOLDING_BIKE",
  "ELECTRIC_BIKE",
  "CARGO_BIKE",
  "FIXIE_BIKE",
  "GRAVEL_BIKE",
  "RECUMBENT_BIKE",
  "ELECTRIC_CITY_BIKE",
  "ELECTRIC_ROAD_BIKE",
  "ELECTRIC_FOLDING_BIKE",
  "ELECTRIC_CARGO_BIKE",
  "ELECTRIC_FIXIE_BIKE",
  "ELECTRIC_HYBRID_BIKE",
  "ELECTRIC_GRAVEL_BIKE",
  "ELECTRIC_RECUMBENT_BIKE",
  "SCOOTER",
  "BIG_WHEEL_SCOOTER",
  "ELECTRIC_SCOOTER",
] as const;

export type BikeType = (typeof BIKE_TYPES)[number];

export const BIKE_TYPE_LABELS: Record<BikeType, string> = {
  CITY_BIKE: "City Bike",
  ROAD_BIKE: "Road Bike",
  MOUNTAIN_BIKE: "Mountain Bike",
  HYBRID_BIKE: "Hybrid Bike",
  FOLDING_BIKE: "Folding Bike",
  ELECTRIC_BIKE: "E-Bike",
  CARGO_BIKE: "Cargo Bike",
  FIXIE_BIKE: "Fixie Bike",
  GRAVEL_BIKE: "Gravel Bike",
  RECUMBENT_BIKE: "Recumbent Bike",
  ELECTRIC_CITY_BIKE: "E-City Bike",
  ELECTRIC_ROAD_BIKE: "E-Road Bike",
  ELECTRIC_FOLDING_BIKE: "E-Folding Bike",
  ELECTRIC_CARGO_BIKE: "E-Cargo Bike",
  ELECTRIC_FIXIE_BIKE: "E-Fixie Bike",
  ELECTRIC_HYBRID_BIKE: "E-Hybrid Bike",
  ELECTRIC_GRAVEL_BIKE: "E-Gravel Bike",
  ELECTRIC_RECUMBENT_BIKE: "E-Recumbent Bike",
  SCOOTER: "Scooter",
  BIG_WHEEL_SCOOTER: "Big Wheel Scooter",
  ELECTRIC_SCOOTER: "E-Scooter",
};
